const Headers = [
  { header: 'name', key: 'name' },
  { header: 'rtu', key: 'rtu' },
  { header: 'estacion', key: 'estacion' },
  { header: 'TYPE', key: 'type' },
  { header: 'description', key: 'description' },
  { header: 'iengr.rawmin', key: 'iengrRawmin' },
  { header: 'iengr.rawmax', key: 'iengrRawmax' },
  { header: 'iengr.egumin', key: 'iengrEgumin' },
  { header: 'iengr.egumax', key: 'iengrEgumax' },
  { header: 'iengr.scaleraw', key: 'iengrScaleraw' },
  { header: 'units', key: 'units' },
  { header: 'Revisión', key: 'revision' },
  { header: 'Comentarios', key: 'comentarios' },
  { header: 'Comentarios EMASESA', key: 'comentariosEmasesa' },
  { header: 'SC_AA', key: 'scaa' },
  { header: 'SC_ER', key: 'scer' },
  { header: 'SC_Servicio', key: 'scServicio' },
  { header: 'SC_Proceso', key: 'scProceso' },
  { header: 'SC_Instalacion', key: 'scInstalacion' },
  { header: 'SC_Activo', key: 'scActivo' },
  { header: 'Descripcion Activo', key: 'descripcionActivo' },
  { header: 'SC_Atributo', key: 'scAtributo' },
  { header: 'SC_Completo', key: 'scCompleto' },
  { header: 'hilow.doit', key: 'hilowDoit' },
  { header: 'hilow.doitdoit', key: 'hilowDoitdoit' },
  { header: 'hilow.dead', key: 'hilowDead' },
  { header: 'hilow.lolim', key: 'hilowLolim' },
  { header: 'hilow.hilim', key: 'hilowHilim' },
  { header: 'hilow.lololim', key: 'hilowLololim' },
  { header: 'hilow.hihilim', key: 'hilowHihilim' },
  { header: 'anain.type', key: 'anainType' },
  { header: 'scale', key: 'scale' },
  { header: 'abnrm_state_alm[2] (Estado 0)', key: 'abnrmStateAlmZero' },
  { header: 'abnrm_state_alm[1] (Estado 1)', key: 'abnrmStateAlmOne' },
  { header: 'flag.bmsg', key: 'flagBmsg' },
  { header: 'Output_cmd_0 (Comm. 0)', key: 'outputCmdZero' },
  { header: 'Output_cmd_2 (Comm. 2 - Estado 0)', key: 'outputCmdTwo' },
  { header: 'Output_cmd_1 (Comm. 1 - Estado 1)', key: 'outputCmdOne' },
  { header: 'Output_cmd_3 (Comm. 3)', key: 'outputCmdThree' },
  { header: 'anain.iospec.external', key: 'anainIospecExternal' },
  { header: 'inbit.bitdef[0].iospec.external', key: 'inbitBitdefZeroIospecExternal' },
  { header: 'inbit.bitdef[1].iospec.external', key: 'inbitBitdefOneIospecExternal' },
  { header: 'accin.iospec.external', key: 'accinIospecExternal' },
  { header: 'anain.iospec.external2', key: 'anainIospecExternalTwo' },
  { header: 'INPUT', key: 'input' },
  { header: 'anaout.iospec.external', key: 'anaoutIospecExternal' },
  { header: 'outs[1].iospec.external', key: 'outsOneIospecExternal' },
  { header: 'outs[2].iospec.external', key: 'outsTwoIospecExternal' },
  { header: 'OUTPUT', key: 'output' },
  { header: 'sustainCOSalarm', key: 'sustainCosAlarm' },
  { header: 'elemento', key: 'elemento' },
  { header: 'tipoelemento', key: 'tipoElemento' },
  { header: 'cutout.activo', key: 'cutoutActivo' },
  { header: 'hilow.dinamica', key: 'hilowDinamica' },
  { header: 'suppressionType', key: 'suppressionType' },
  { header: 'parentStrKey', key: 'parentStrKey' },
  { header: 'timeout', key: 'timeout' },
  { header: 'rtnAlmTimeout', key: 'rtnAlmTimeout' },
  { header: 'holdOffTimeout', key: 'holdOffTimeout' },
  { header: 'flag.alminh', key: 'flagAlminh' },
  { header: 'flag.clrinh', key: 'flagClrinh' },
  { header: 'ALARMA', key: 'alarma' },
  { header: 'flag.evtinh', key: 'flagEvtinh' },
  { header: 'flag.cevinh', key: 'flagCevinh' },
  { header: 'EVENTO', key: 'evento' },
  { header: 'HISTORICO', key: 'historico' },
  { header: 'REVISION', key: 'revisionColumnaFinal' }
];

export default Headers;
