const Headers = [
  { header: 'ID', key: 'id' },
  { header: 'Utilizada', key: 'utilizada' },
  { header: 'Automatico', key: 'automatico' },
  { header: 'Descartable', key: 'descartable' },
  { header: 'Revisar', key: 'revisar' },
  { header: 'FueraPlantilla', key: 'fueraPlantilla' },
  { header: 'VAR_0', key: 'varCero' },
  { header: 'Comentarios', key: 'comentarios' },
  { header: 'Script', key: 'script' },
  { header: 'Estacion', key: 'estacion' },
  { header: 'Agrupador', key: 'agrupador' },
  { header: 'Instancia', key: 'instancia' },
  { header: 'Atributo', key: 'atributo' },
  { header: 'Nombre', key: 'nombre' },
  { header: 'Tipo', key: 'tipo' },
  { header: 'Grupo', key: 'grupo' },
  { header: 'Descripcion', key: 'descripcion' },
  { header: 'ValorInicial', key: 'valorInicial' },
  { header: 'OffMsg', key: 'offMsg' },
  { header: 'OnMsg', key: 'onMsg' },
  { header: 'AccessName', key: 'accessName' },
  { header: 'DireccionPLC', key: 'direccionPlc' },
  { header: 'ReadOnly', key: 'readOnly' },
  { header: 'Invertida', key: 'invertida' },
  { header: 'EngUnits', key: 'engUnits' },
  { header: 'MinValue', key: 'minValue' },
  { header: 'MaxValue', key: 'maxValue' },
  { header: 'MinRaw', key: 'minRaw' },
  { header: 'MaxRaw', key: 'maxRaw' },
  { header: 'Historico', key: 'historico' },
  { header: 'HistMax', key: 'histMax' },
  { header: 'HistMin', key: 'histMin' },
  { header: 'Evento', key: 'evento' },
  { header: 'AlarmState', key: 'alarmState' },
  { header: 'AlarmPri', key: 'alarmPri' },
  { header: 'LoLoAlarmState', key: 'loLoAlarmState' },
  { header: 'LoLoAlarmValue', key: 'loLoAlarmValue' },
  { header: 'LoLoAlarmPri', key: 'loLoAlarmPri' },
  { header: 'LoAlarmState', key: 'loAlarmState'},
  { header: 'LoAlarmValue', key: 'loAlarmValue' },
  { header: 'LoAlarmPri', key: 'loAlarmPri' },
  { header: 'HiAlarmState', key: 'hiAlarmState' },
  { header: 'HiAlarmValue', key: 'hiAlarmValue' },
  { header: 'HiAlarmPri', key: 'hiAlarmPri' },
  { header: 'HiHiAlarmState', key: 'hiHiAlarmState' },
  { header: 'HiHiAlarmValue', key: 'hiHiAlarmValue' },
  { header: 'HiHiAlarmPri', key: 'hiHiAlarmPri' }
];

export default Headers;